/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const BillCategory = IDL.Variant({
  'Shipping' : IDL.Null,
  'Rent' : IDL.Null,
  'ProfessionalServices' : IDL.Null,
  'Software' : IDL.Null,
  'Packaging' : IDL.Null,
  'Other' : IDL.Null,
  'Ingredients' : IDL.Null,
  'Marketing' : IDL.Null,
});
export const VatRate = IDL.Variant({
  'Five' : IDL.Null,
  'Zero' : IDL.Null,
  'Twenty' : IDL.Null,
});
export const CreateBillData = IDL.Record({
  'supplierName' : IDL.Text,
  'date' : Timestamp,
  'dueDate' : Timestamp,
  'linkedProductIds' : IDL.Vec(IDL.Nat),
  'notes' : IDL.Text,
  'category' : BillCategory,
  'vatAmount' : IDL.Float64,
  'receiptFileId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'supplierId' : IDL.Nat,
  'vatRate' : VatRate,
});
export const BillStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Overdue' : IDL.Null,
  'Unpaid' : IDL.Null,
});
export const BillShared = IDL.Record({
  'id' : IDL.Nat,
  'status' : BillStatus,
  'supplierName' : IDL.Text,
  'date' : Timestamp,
  'dueDate' : Timestamp,
  'linkedProductIds' : IDL.Vec(IDL.Nat),
  'paidDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'billNumber' : IDL.Text,
  'category' : BillCategory,
  'vatAmount' : IDL.Float64,
  'receiptFileId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'supplierId' : IDL.Nat,
  'vatRate' : VatRate,
});
export const CustomerType = IDL.Variant({
  'DTC' : IDL.Null,
  'Wholesale' : IDL.Null,
});
export const CreateCustomerData = IDL.Record({
  'customerType' : CustomerType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerType' : CustomerType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceLineItem = IDL.Record({
  'lineTotal' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'vatAmount' : IDL.Float64,
  'vatRate' : VatRate,
});
export const RecurringFrequency = IDL.Variant({
  'Weekly' : IDL.Null,
  'Monthly' : IDL.Null,
});
export const CreateInvoiceData = IDL.Record({
  'issueDate' : Timestamp,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'isRecurring' : IDL.Bool,
  'dueDate' : Timestamp,
  'totalVat' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'recurringFrequency' : IDL.Opt(RecurringFrequency),
  'subtotal' : IDL.Float64,
});
export const InvoiceStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
  'Overdue' : IDL.Null,
});
export const InvoiceShared = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : Timestamp,
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'isRecurring' : IDL.Bool,
  'dueDate' : Timestamp,
  'totalVat' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'paidDate' : IDL.Opt(Timestamp),
  'invoiceNumber' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'recurringFrequency' : IDL.Opt(RecurringFrequency),
  'subtotal' : IDL.Float64,
});
export const CreateProductData = IDL.Record({
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'reorderPoint' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'salePrice' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const ProductShared = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'reorderPoint' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'salePrice' : IDL.Float64,
  'margin' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const CreateSupplierData = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'category' : BillCategory,
  'phone' : IDL.Text,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'category' : BillCategory,
  'phone' : IDL.Text,
});
export const AgedBucket = IDL.Record({
  'title' : IDL.Text,
  'total' : IDL.Float64,
  'count' : IDL.Nat,
});
export const AgedReport = IDL.Record({
  'grandTotal' : IDL.Float64,
  'buckets' : IDL.Vec(AgedBucket),
});
export const MonthlyCashFlow = IDL.Record({
  'month' : IDL.Nat,
  'netFlow' : IDL.Float64,
  'year' : IDL.Nat,
  'inflow' : IDL.Float64,
  'runningBalance' : IDL.Float64,
  'outflow' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'overdueInvoices' : IDL.Vec(InvoiceShared),
  'lowStockProducts' : IDL.Vec(ProductShared),
  'netProfitThisMonth' : IDL.Float64,
  'billsDueIn14Days' : IDL.Vec(BillShared),
  'totalCashBalance' : IDL.Float64,
  'revenueThisMonth' : IDL.Float64,
  'expensesThisMonth' : IDL.Float64,
});
export const ExpenseCategory = IDL.Record({
  'category' : IDL.Text,
  'amount' : IDL.Float64,
  'prevAmount' : IDL.Float64,
  'flagged' : IDL.Bool,
});
export const ExpenseSummary = IDL.Record({
  'categories' : IDL.Vec(ExpenseCategory),
  'total' : IDL.Float64,
  'endDate' : Timestamp,
  'startDate' : Timestamp,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Nat,
  'revenue' : IDL.Float64,
  'expenses' : IDL.Float64,
  'year' : IDL.Nat,
  'topCustomers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'topExpenseCategories' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'profit' : IDL.Float64,
});
export const ProfitAndLossReport = IDL.Record({
  'prevCogs' : IDL.Float64,
  'revenue' : IDL.Float64,
  'endDate' : Timestamp,
  'expensesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'grossProfit' : IDL.Float64,
  'cogs' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'prevRevenue' : IDL.Float64,
  'prevGrossProfit' : IDL.Float64,
  'prevNetProfit' : IDL.Float64,
  'netProfit' : IDL.Float64,
  'startDate' : Timestamp,
});
export const VatSummary = IDL.Record({
  'quarter' : IDL.Nat,
  'year' : IDL.Nat,
  'vatCollected' : IDL.Float64,
  'netVatOwed' : IDL.Float64,
  'vatPaid' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createBill' : IDL.Func([CreateBillData], [BillShared], []),
  'createCustomer' : IDL.Func([CreateCustomerData], [Customer], []),
  'createInvoice' : IDL.Func([CreateInvoiceData], [InvoiceShared], []),
  'createProduct' : IDL.Func([CreateProductData], [ProductShared], []),
  'createSupplier' : IDL.Func([CreateSupplierData], [Supplier], []),
  'getAgedPayables' : IDL.Func([], [AgedReport], ['query']),
  'getAgedReceivables' : IDL.Func([], [AgedReport], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(BillShared)], ['query']),
  'getBills' : IDL.Func([], [IDL.Vec(BillShared)], ['query']),
  'getCashFlow' : IDL.Func([IDL.Nat], [IDL.Vec(MonthlyCashFlow)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerInvoiceHistory' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'invoices' : IDL.Vec(InvoiceShared),
          'outstandingBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExpenseSummary' : IDL.Func(
      [Timestamp, Timestamp],
      [ExpenseSummary],
      ['query'],
    ),
  'getInventoryStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAtCost' : IDL.Float64,
          'totalAtSale' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceShared)], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(InvoiceShared)], ['query']),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlySummary],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductShared)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductShared)], ['query']),
  'getProfitAndLoss' : IDL.Func(
      [Timestamp, Timestamp],
      [ProfitAndLossReport],
      ['query'],
    ),
  'getSupplier' : IDL.Func([IDL.Nat], [IDL.Opt(Supplier)], ['query']),
  'getSupplierBillHistory' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'bills' : IDL.Vec(BillShared),
          'outstandingBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getVatSummary' : IDL.Func([IDL.Nat, IDL.Nat], [VatSummary], ['query']),
  'initializeSampleData' : IDL.Func([], [IDL.Bool], []),
  'markBillPaid' : IDL.Func([IDL.Nat, Timestamp], [IDL.Opt(BillShared)], []),
  'markInvoicePaid' : IDL.Func(
      [IDL.Nat, Timestamp],
      [IDL.Opt(InvoiceShared)],
      [],
    ),
  'updateBill' : IDL.Func([IDL.Nat, CreateBillData], [IDL.Opt(BillShared)], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, CreateCustomerData],
      [IDL.Opt(Customer)],
      [],
    ),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, CreateInvoiceData],
      [IDL.Opt(InvoiceShared)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, CreateProductData],
      [IDL.Opt(ProductShared)],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [IDL.Nat, CreateSupplierData],
      [IDL.Opt(Supplier)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const BillCategory = IDL.Variant({
    'Shipping' : IDL.Null,
    'Rent' : IDL.Null,
    'ProfessionalServices' : IDL.Null,
    'Software' : IDL.Null,
    'Packaging' : IDL.Null,
    'Other' : IDL.Null,
    'Ingredients' : IDL.Null,
    'Marketing' : IDL.Null,
  });
  const VatRate = IDL.Variant({
    'Five' : IDL.Null,
    'Zero' : IDL.Null,
    'Twenty' : IDL.Null,
  });
  const CreateBillData = IDL.Record({
    'supplierName' : IDL.Text,
    'date' : Timestamp,
    'dueDate' : Timestamp,
    'linkedProductIds' : IDL.Vec(IDL.Nat),
    'notes' : IDL.Text,
    'category' : BillCategory,
    'vatAmount' : IDL.Float64,
    'receiptFileId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'supplierId' : IDL.Nat,
    'vatRate' : VatRate,
  });
  const BillStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Overdue' : IDL.Null,
    'Unpaid' : IDL.Null,
  });
  const BillShared = IDL.Record({
    'id' : IDL.Nat,
    'status' : BillStatus,
    'supplierName' : IDL.Text,
    'date' : Timestamp,
    'dueDate' : Timestamp,
    'linkedProductIds' : IDL.Vec(IDL.Nat),
    'paidDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'billNumber' : IDL.Text,
    'category' : BillCategory,
    'vatAmount' : IDL.Float64,
    'receiptFileId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'supplierId' : IDL.Nat,
    'vatRate' : VatRate,
  });
  const CustomerType = IDL.Variant({
    'DTC' : IDL.Null,
    'Wholesale' : IDL.Null,
  });
  const CreateCustomerData = IDL.Record({
    'customerType' : CustomerType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerType' : CustomerType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceLineItem = IDL.Record({
    'lineTotal' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'vatAmount' : IDL.Float64,
    'vatRate' : VatRate,
  });
  const RecurringFrequency = IDL.Variant({
    'Weekly' : IDL.Null,
    'Monthly' : IDL.Null,
  });
  const CreateInvoiceData = IDL.Record({
    'issueDate' : Timestamp,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'isRecurring' : IDL.Bool,
    'dueDate' : Timestamp,
    'totalVat' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'recurringFrequency' : IDL.Opt(RecurringFrequency),
    'subtotal' : IDL.Float64,
  });
  const InvoiceStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
    'Overdue' : IDL.Null,
  });
  const InvoiceShared = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : Timestamp,
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'isRecurring' : IDL.Bool,
    'dueDate' : Timestamp,
    'totalVat' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'paidDate' : IDL.Opt(Timestamp),
    'invoiceNumber' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'recurringFrequency' : IDL.Opt(RecurringFrequency),
    'subtotal' : IDL.Float64,
  });
  const CreateProductData = IDL.Record({
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'reorderPoint' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'salePrice' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const ProductShared = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'reorderPoint' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'salePrice' : IDL.Float64,
    'margin' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const CreateSupplierData = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'category' : BillCategory,
    'phone' : IDL.Text,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'category' : BillCategory,
    'phone' : IDL.Text,
  });
  const AgedBucket = IDL.Record({
    'title' : IDL.Text,
    'total' : IDL.Float64,
    'count' : IDL.Nat,
  });
  const AgedReport = IDL.Record({
    'grandTotal' : IDL.Float64,
    'buckets' : IDL.Vec(AgedBucket),
  });
  const MonthlyCashFlow = IDL.Record({
    'month' : IDL.Nat,
    'netFlow' : IDL.Float64,
    'year' : IDL.Nat,
    'inflow' : IDL.Float64,
    'runningBalance' : IDL.Float64,
    'outflow' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'overdueInvoices' : IDL.Vec(InvoiceShared),
    'lowStockProducts' : IDL.Vec(ProductShared),
    'netProfitThisMonth' : IDL.Float64,
    'billsDueIn14Days' : IDL.Vec(BillShared),
    'totalCashBalance' : IDL.Float64,
    'revenueThisMonth' : IDL.Float64,
    'expensesThisMonth' : IDL.Float64,
  });
  const ExpenseCategory = IDL.Record({
    'category' : IDL.Text,
    'amount' : IDL.Float64,
    'prevAmount' : IDL.Float64,
    'flagged' : IDL.Bool,
  });
  const ExpenseSummary = IDL.Record({
    'categories' : IDL.Vec(ExpenseCategory),
    'total' : IDL.Float64,
    'endDate' : Timestamp,
    'startDate' : Timestamp,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Nat,
    'revenue' : IDL.Float64,
    'expenses' : IDL.Float64,
    'year' : IDL.Nat,
    'topCustomers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'topExpenseCategories' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'profit' : IDL.Float64,
  });
  const ProfitAndLossReport = IDL.Record({
    'prevCogs' : IDL.Float64,
    'revenue' : IDL.Float64,
    'endDate' : Timestamp,
    'expensesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'grossProfit' : IDL.Float64,
    'cogs' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'prevRevenue' : IDL.Float64,
    'prevGrossProfit' : IDL.Float64,
    'prevNetProfit' : IDL.Float64,
    'netProfit' : IDL.Float64,
    'startDate' : Timestamp,
  });
  const VatSummary = IDL.Record({
    'quarter' : IDL.Nat,
    'year' : IDL.Nat,
    'vatCollected' : IDL.Float64,
    'netVatOwed' : IDL.Float64,
    'vatPaid' : IDL.Float64,
  });
  
  return IDL.Service({
    'createBill' : IDL.Func([CreateBillData], [BillShared], []),
    'createCustomer' : IDL.Func([CreateCustomerData], [Customer], []),
    'createInvoice' : IDL.Func([CreateInvoiceData], [InvoiceShared], []),
    'createProduct' : IDL.Func([CreateProductData], [ProductShared], []),
    'createSupplier' : IDL.Func([CreateSupplierData], [Supplier], []),
    'getAgedPayables' : IDL.Func([], [AgedReport], ['query']),
    'getAgedReceivables' : IDL.Func([], [AgedReport], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(BillShared)], ['query']),
    'getBills' : IDL.Func([], [IDL.Vec(BillShared)], ['query']),
    'getCashFlow' : IDL.Func([IDL.Nat], [IDL.Vec(MonthlyCashFlow)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerInvoiceHistory' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'invoices' : IDL.Vec(InvoiceShared),
            'outstandingBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExpenseSummary' : IDL.Func(
        [Timestamp, Timestamp],
        [ExpenseSummary],
        ['query'],
      ),
    'getInventoryStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAtCost' : IDL.Float64,
            'totalAtSale' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceShared)], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(InvoiceShared)], ['query']),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlySummary],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductShared)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductShared)], ['query']),
    'getProfitAndLoss' : IDL.Func(
        [Timestamp, Timestamp],
        [ProfitAndLossReport],
        ['query'],
      ),
    'getSupplier' : IDL.Func([IDL.Nat], [IDL.Opt(Supplier)], ['query']),
    'getSupplierBillHistory' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'bills' : IDL.Vec(BillShared),
            'outstandingBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getVatSummary' : IDL.Func([IDL.Nat, IDL.Nat], [VatSummary], ['query']),
    'initializeSampleData' : IDL.Func([], [IDL.Bool], []),
    'markBillPaid' : IDL.Func([IDL.Nat, Timestamp], [IDL.Opt(BillShared)], []),
    'markInvoicePaid' : IDL.Func(
        [IDL.Nat, Timestamp],
        [IDL.Opt(InvoiceShared)],
        [],
      ),
    'updateBill' : IDL.Func(
        [IDL.Nat, CreateBillData],
        [IDL.Opt(BillShared)],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, CreateCustomerData],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, CreateInvoiceData],
        [IDL.Opt(InvoiceShared)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, CreateProductData],
        [IDL.Opt(ProductShared)],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [IDL.Nat, CreateSupplierData],
        [IDL.Opt(Supplier)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };