/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgedBucket {
  'title' : string,
  'total' : number,
  'count' : bigint,
}
export interface AgedReport {
  'grandTotal' : number,
  'buckets' : Array<AgedBucket>,
}
export type BillCategory = { 'Shipping' : null } |
  { 'Rent' : null } |
  { 'ProfessionalServices' : null } |
  { 'Software' : null } |
  { 'Packaging' : null } |
  { 'Other' : null } |
  { 'Ingredients' : null } |
  { 'Marketing' : null };
export interface BillShared {
  'id' : bigint,
  'status' : BillStatus,
  'supplierName' : string,
  'date' : Timestamp,
  'dueDate' : Timestamp,
  'linkedProductIds' : Array<bigint>,
  'paidDate' : [] | [Timestamp],
  'notes' : string,
  'billNumber' : string,
  'category' : BillCategory,
  'vatAmount' : number,
  'receiptFileId' : [] | [string],
  'amount' : number,
  'supplierId' : bigint,
  'vatRate' : VatRate,
}
export type BillStatus = { 'Paid' : null } |
  { 'Overdue' : null } |
  { 'Unpaid' : null };
export interface CreateBillData {
  'supplierName' : string,
  'date' : Timestamp,
  'dueDate' : Timestamp,
  'linkedProductIds' : Array<bigint>,
  'notes' : string,
  'category' : BillCategory,
  'vatAmount' : number,
  'receiptFileId' : [] | [string],
  'amount' : number,
  'supplierId' : bigint,
  'vatRate' : VatRate,
}
export interface CreateCustomerData {
  'customerType' : CustomerType,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface CreateInvoiceData {
  'issueDate' : Timestamp,
  'customerName' : string,
  'lineItems' : Array<InvoiceLineItem>,
  'isRecurring' : boolean,
  'dueDate' : Timestamp,
  'totalVat' : number,
  'grandTotal' : number,
  'notes' : string,
  'customerId' : bigint,
  'recurringFrequency' : [] | [RecurringFrequency],
  'subtotal' : number,
}
export interface CreateProductData {
  'sku' : string,
  'stockQuantity' : bigint,
  'reorderPoint' : bigint,
  'name' : string,
  'description' : string,
  'salePrice' : number,
  'costPrice' : number,
}
export interface CreateSupplierData {
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'category' : BillCategory,
  'phone' : string,
}
export interface Customer {
  'id' : bigint,
  'customerType' : CustomerType,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export type CustomerType = { 'DTC' : null } |
  { 'Wholesale' : null };
export interface DashboardStats {
  'overdueInvoices' : Array<InvoiceShared>,
  'lowStockProducts' : Array<ProductShared>,
  'netProfitThisMonth' : number,
  'billsDueIn14Days' : Array<BillShared>,
  'totalCashBalance' : number,
  'revenueThisMonth' : number,
  'expensesThisMonth' : number,
}
export interface ExpenseCategory {
  'category' : string,
  'amount' : number,
  'prevAmount' : number,
  'flagged' : boolean,
}
export interface ExpenseSummary {
  'categories' : Array<ExpenseCategory>,
  'total' : number,
  'endDate' : Timestamp,
  'startDate' : Timestamp,
}
export interface InvoiceLineItem {
  'lineTotal' : number,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'vatAmount' : number,
  'vatRate' : VatRate,
}
export interface InvoiceShared {
  'id' : bigint,
  'issueDate' : Timestamp,
  'customerName' : string,
  'status' : InvoiceStatus,
  'lineItems' : Array<InvoiceLineItem>,
  'isRecurring' : boolean,
  'dueDate' : Timestamp,
  'totalVat' : number,
  'grandTotal' : number,
  'paidDate' : [] | [Timestamp],
  'invoiceNumber' : string,
  'notes' : string,
  'customerId' : bigint,
  'recurringFrequency' : [] | [RecurringFrequency],
  'subtotal' : number,
}
export type InvoiceStatus = { 'Paid' : null } |
  { 'Sent' : null } |
  { 'Draft' : null } |
  { 'Overdue' : null };
export interface MonthlyCashFlow {
  'month' : bigint,
  'netFlow' : number,
  'year' : bigint,
  'inflow' : number,
  'runningBalance' : number,
  'outflow' : number,
}
export interface MonthlySummary {
  'month' : bigint,
  'revenue' : number,
  'expenses' : number,
  'year' : bigint,
  'topCustomers' : Array<[string, number]>,
  'topExpenseCategories' : Array<[string, number]>,
  'profit' : number,
}
export interface ProductShared {
  'id' : bigint,
  'sku' : string,
  'stockQuantity' : bigint,
  'reorderPoint' : bigint,
  'name' : string,
  'description' : string,
  'salePrice' : number,
  'margin' : number,
  'costPrice' : number,
}
export interface ProfitAndLossReport {
  'prevCogs' : number,
  'revenue' : number,
  'endDate' : Timestamp,
  'expensesByCategory' : Array<[string, number]>,
  'grossProfit' : number,
  'cogs' : number,
  'totalExpenses' : number,
  'prevRevenue' : number,
  'prevGrossProfit' : number,
  'prevNetProfit' : number,
  'netProfit' : number,
  'startDate' : Timestamp,
}
export type RecurringFrequency = { 'Weekly' : null } |
  { 'Monthly' : null };
export interface Supplier {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'category' : BillCategory,
  'phone' : string,
}
export type Timestamp = bigint;
export type VatRate = { 'Five' : null } |
  { 'Zero' : null } |
  { 'Twenty' : null };
export interface VatSummary {
  'quarter' : bigint,
  'year' : bigint,
  'vatCollected' : number,
  'netVatOwed' : number,
  'vatPaid' : number,
}
export interface _SERVICE {
  'createBill' : ActorMethod<[CreateBillData], BillShared>,
  'createCustomer' : ActorMethod<[CreateCustomerData], Customer>,
  'createInvoice' : ActorMethod<[CreateInvoiceData], InvoiceShared>,
  'createProduct' : ActorMethod<[CreateProductData], ProductShared>,
  'createSupplier' : ActorMethod<[CreateSupplierData], Supplier>,
  'getAgedPayables' : ActorMethod<[], AgedReport>,
  'getAgedReceivables' : ActorMethod<[], AgedReport>,
  'getBill' : ActorMethod<[bigint], [] | [BillShared]>,
  'getBills' : ActorMethod<[], Array<BillShared>>,
  'getCashFlow' : ActorMethod<[bigint], Array<MonthlyCashFlow>>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerInvoiceHistory' : ActorMethod<
    [bigint],
    { 'invoices' : Array<InvoiceShared>, 'outstandingBalance' : number }
  >,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExpenseSummary' : ActorMethod<[Timestamp, Timestamp], ExpenseSummary>,
  'getInventoryStats' : ActorMethod<
    [],
    { 'totalAtCost' : number, 'totalAtSale' : number }
  >,
  'getInvoice' : ActorMethod<[bigint], [] | [InvoiceShared]>,
  'getInvoices' : ActorMethod<[], Array<InvoiceShared>>,
  'getMonthlySummary' : ActorMethod<[bigint, bigint], MonthlySummary>,
  'getProduct' : ActorMethod<[bigint], [] | [ProductShared]>,
  'getProducts' : ActorMethod<[], Array<ProductShared>>,
  'getProfitAndLoss' : ActorMethod<[Timestamp, Timestamp], ProfitAndLossReport>,
  'getSupplier' : ActorMethod<[bigint], [] | [Supplier]>,
  'getSupplierBillHistory' : ActorMethod<
    [bigint],
    { 'bills' : Array<BillShared>, 'outstandingBalance' : number }
  >,
  'getSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getVatSummary' : ActorMethod<[bigint, bigint], VatSummary>,
  'initializeSampleData' : ActorMethod<[], boolean>,
  'markBillPaid' : ActorMethod<[bigint, Timestamp], [] | [BillShared]>,
  'markInvoicePaid' : ActorMethod<[bigint, Timestamp], [] | [InvoiceShared]>,
  'updateBill' : ActorMethod<[bigint, CreateBillData], [] | [BillShared]>,
  'updateCustomer' : ActorMethod<[bigint, CreateCustomerData], [] | [Customer]>,
  'updateInvoice' : ActorMethod<
    [bigint, CreateInvoiceData],
    [] | [InvoiceShared]
  >,
  'updateProduct' : ActorMethod<
    [bigint, CreateProductData],
    [] | [ProductShared]
  >,
  'updateSupplier' : ActorMethod<[bigint, CreateSupplierData], [] | [Supplier]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];