/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExpenseSummary {
    categories: Array<ExpenseCategory>;
    total: number;
    endDate: Timestamp;
    startDate: Timestamp;
}
export type Timestamp = bigint;
export interface ProductShared {
    id: bigint;
    sku: string;
    stockQuantity: bigint;
    reorderPoint: bigint;
    name: string;
    description: string;
    salePrice: number;
    margin: number;
    costPrice: number;
}
export interface MonthlySummary {
    month: bigint;
    revenue: number;
    expenses: number;
    year: bigint;
    topCustomers: Array<[string, number]>;
    topExpenseCategories: Array<[string, number]>;
    profit: number;
}
export interface MonthlyCashFlow {
    month: bigint;
    netFlow: number;
    year: bigint;
    inflow: number;
    runningBalance: number;
    outflow: number;
}
export interface CreateInvoiceData {
    issueDate: Timestamp;
    customerName: string;
    lineItems: Array<InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: Timestamp;
    totalVat: number;
    grandTotal: number;
    notes: string;
    customerId: bigint;
    recurringFrequency?: RecurringFrequency;
    subtotal: number;
}
export interface VatSummary {
    quarter: bigint;
    year: bigint;
    vatCollected: number;
    netVatOwed: number;
    vatPaid: number;
}
export interface AgedBucket {
    title: string;
    total: number;
    count: bigint;
}
export interface InvoiceShared {
    id: bigint;
    issueDate: Timestamp;
    customerName: string;
    status: InvoiceStatus;
    lineItems: Array<InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: Timestamp;
    totalVat: number;
    grandTotal: number;
    paidDate?: Timestamp;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    recurringFrequency?: RecurringFrequency;
    subtotal: number;
}
export interface AgedReport {
    grandTotal: number;
    buckets: Array<AgedBucket>;
}
export interface ProfitAndLossReport {
    prevCogs: number;
    revenue: number;
    endDate: Timestamp;
    expensesByCategory: Array<[string, number]>;
    grossProfit: number;
    cogs: number;
    totalExpenses: number;
    prevRevenue: number;
    prevGrossProfit: number;
    prevNetProfit: number;
    netProfit: number;
    startDate: Timestamp;
}
export interface ExpenseCategory {
    category: string;
    amount: number;
    prevAmount: number;
    flagged: boolean;
}
export interface CreateSupplierData {
    name: string;
    email: string;
    address: string;
    notes: string;
    category: BillCategory;
    phone: string;
}
export interface ExtractedBillData {
    supplierName?: string;
    date?: string;
    invoiceNumber?: string;
    vatAmount?: number;
    confidence: string;
    amount?: number;
}
export interface DashboardStats {
    overdueInvoices: Array<InvoiceShared>;
    lowStockProducts: Array<ProductShared>;
    netProfitThisMonth: number;
    billsDueIn14Days: Array<BillShared>;
    totalCashBalance: number;
    revenueThisMonth: number;
    expensesThisMonth: number;
}
export interface Customer {
    id: bigint;
    customerType: CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
}
export interface CreateProductData {
    sku: string;
    stockQuantity: bigint;
    reorderPoint: bigint;
    name: string;
    description: string;
    salePrice: number;
    costPrice: number;
}
export interface BillShared {
    id: bigint;
    status: BillStatus;
    supplierName: string;
    date: Timestamp;
    dueDate: Timestamp;
    linkedProductIds: Array<bigint>;
    paidDate?: Timestamp;
    notes: string;
    billNumber: string;
    category: BillCategory;
    vatAmount: number;
    receiptFileId?: string;
    amount: number;
    supplierId: bigint;
    vatRate: VatRate;
}
export interface CreateCustomerData {
    customerType: CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
}
export interface CreateBillData {
    supplierName: string;
    date: Timestamp;
    dueDate: Timestamp;
    linkedProductIds: Array<bigint>;
    notes: string;
    category: BillCategory;
    vatAmount: number;
    receiptFileId?: string;
    amount: number;
    supplierId: bigint;
    vatRate: VatRate;
}
export interface Supplier {
    id: bigint;
    name: string;
    email: string;
    address: string;
    notes: string;
    category: BillCategory;
    phone: string;
}
export interface InvoiceLineItem {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    unitPrice: number;
    vatAmount: number;
    vatRate: VatRate;
}
export enum BillCategory {
    Shipping = "Shipping",
    Rent = "Rent",
    ProfessionalServices = "ProfessionalServices",
    Software = "Software",
    Packaging = "Packaging",
    Other = "Other",
    Ingredients = "Ingredients",
    Marketing = "Marketing"
}
export enum BillStatus {
    Paid = "Paid",
    Overdue = "Overdue",
    Unpaid = "Unpaid"
}
export enum CustomerType {
    DTC = "DTC",
    Wholesale = "Wholesale"
}
export enum InvoiceStatus {
    Paid = "Paid",
    Sent = "Sent",
    Draft = "Draft",
    Overdue = "Overdue"
}
export enum RecurringFrequency {
    Weekly = "Weekly",
    Monthly = "Monthly"
}
export enum VatRate {
    Five = "Five",
    Zero = "Zero",
    Twenty = "Twenty"
}
export interface backendInterface {
    createBill(data: CreateBillData): Promise<BillShared>;
    createCustomer(data: CreateCustomerData): Promise<Customer>;
    createInvoice(data: CreateInvoiceData): Promise<InvoiceShared>;
    createProduct(data: CreateProductData): Promise<ProductShared>;
    createSupplier(data: CreateSupplierData): Promise<Supplier>;
    extractPdfBillData(pdfText: string): Promise<ExtractedBillData>;
    getAgedPayables(): Promise<AgedReport>;
    getAgedReceivables(): Promise<AgedReport>;
    getBill(id: bigint): Promise<BillShared | null>;
    getBills(): Promise<Array<BillShared>>;
    getCashFlow(year: bigint): Promise<Array<MonthlyCashFlow>>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomerInvoiceHistory(customerId: bigint): Promise<{
        invoices: Array<InvoiceShared>;
        outstandingBalance: number;
    }>;
    getCustomers(): Promise<Array<Customer>>;
    getDashboardStats(): Promise<DashboardStats>;
    getExpenseSummary(startDate: Timestamp, endDate: Timestamp): Promise<ExpenseSummary>;
    getInventoryStats(): Promise<{
        totalAtCost: number;
        totalAtSale: number;
    }>;
    getInvoice(id: bigint): Promise<InvoiceShared | null>;
    getInvoices(): Promise<Array<InvoiceShared>>;
    getMonthlySummary(month: bigint, year: bigint): Promise<MonthlySummary>;
    getProduct(id: bigint): Promise<ProductShared | null>;
    getProducts(): Promise<Array<ProductShared>>;
    getProfitAndLoss(startDate: Timestamp, endDate: Timestamp): Promise<ProfitAndLossReport>;
    getSupplier(id: bigint): Promise<Supplier | null>;
    getSupplierBillHistory(supplierId: bigint): Promise<{
        bills: Array<BillShared>;
        outstandingBalance: number;
    }>;
    getSuppliers(): Promise<Array<Supplier>>;
    getVatSummary(quarter: bigint, year: bigint): Promise<VatSummary>;
    initializeSampleData(): Promise<boolean>;
    markBillPaid(id: bigint, paidDate: Timestamp): Promise<BillShared | null>;
    markInvoicePaid(id: bigint, paidDate: Timestamp): Promise<InvoiceShared | null>;
    updateBill(id: bigint, data: CreateBillData): Promise<BillShared | null>;
    updateCustomer(id: bigint, data: CreateCustomerData): Promise<Customer | null>;
    updateInvoice(id: bigint, data: CreateInvoiceData): Promise<InvoiceShared | null>;
    updateProduct(id: bigint, data: CreateProductData): Promise<ProductShared | null>;
    updateSupplier(id: bigint, data: CreateSupplierData): Promise<Supplier | null>;
    uploadBillAttachment(billId: bigint, fileId: string): Promise<BillShared | null>;
}
import type { BillCategory as _BillCategory, BillShared as _BillShared, BillStatus as _BillStatus, CreateBillData as _CreateBillData, CreateCustomerData as _CreateCustomerData, CreateInvoiceData as _CreateInvoiceData, CreateSupplierData as _CreateSupplierData, Customer as _Customer, CustomerType as _CustomerType, DashboardStats as _DashboardStats, ExtractedBillData as _ExtractedBillData, InvoiceLineItem as _InvoiceLineItem, InvoiceShared as _InvoiceShared, InvoiceStatus as _InvoiceStatus, ProductShared as _ProductShared, RecurringFrequency as _RecurringFrequency, Supplier as _Supplier, Timestamp as _Timestamp, VatRate as _VatRate } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBill(arg0: CreateBillData): Promise<BillShared> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(to_candid_CreateBillData_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BillShared_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(to_candid_CreateBillData_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BillShared_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomer(arg0: CreateCustomerData): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_CreateCustomerData_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Customer_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_CreateCustomerData_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Customer_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: CreateInvoiceData): Promise<InvoiceShared> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_CreateInvoiceData_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InvoiceShared_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_CreateInvoiceData_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InvoiceShared_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: CreateProductData): Promise<ProductShared> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async createSupplier(arg0: CreateSupplierData): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplier(to_candid_CreateSupplierData_n42(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Supplier_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplier(to_candid_CreateSupplierData_n42(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Supplier_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async extractPdfBillData(arg0: string): Promise<ExtractedBillData> {
        if (this.processError) {
            try {
                const result = await this.actor.extractPdfBillData(arg0);
                return from_candid_ExtractedBillData_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extractPdfBillData(arg0);
            return from_candid_ExtractedBillData_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgedPayables(): Promise<AgedReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgedPayables();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgedPayables();
            return result;
        }
    }
    async getAgedReceivables(): Promise<AgedReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgedReceivables();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgedReceivables();
            return result;
        }
    }
    async getBill(arg0: bigint): Promise<BillShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBills(): Promise<Array<BillShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashFlow(arg0: bigint): Promise<Array<MonthlyCashFlow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashFlow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashFlow(arg0);
            return result;
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerInvoiceHistory(arg0: bigint): Promise<{
        invoices: Array<InvoiceShared>;
        outstandingBalance: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerInvoiceHistory(arg0);
                return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerInvoiceHistory(arg0);
            return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseSummary(arg0: Timestamp, arg1: Timestamp): Promise<ExpenseSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseSummary(arg0, arg1);
            return result;
        }
    }
    async getInventoryStats(): Promise<{
        totalAtCost: number;
        totalAtSale: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryStats();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<InvoiceShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(): Promise<Array<InvoiceShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: bigint, arg1: bigint): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0, arg1);
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<ProductShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<ProductShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getProfitAndLoss(arg0: Timestamp, arg1: Timestamp): Promise<ProfitAndLossReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitAndLoss(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitAndLoss(arg0, arg1);
            return result;
        }
    }
    async getSupplier(arg0: bigint): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierBillHistory(arg0: bigint): Promise<{
        bills: Array<BillShared>;
        outstandingBalance: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierBillHistory(arg0);
                return from_candid_record_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierBillHistory(arg0);
            return from_candid_record_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuppliers();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuppliers();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVatSummary(arg0: bigint, arg1: bigint): Promise<VatSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getVatSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVatSummary(arg0, arg1);
            return result;
        }
    }
    async initializeSampleData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSampleData();
            return result;
        }
    }
    async markBillPaid(arg0: bigint, arg1: Timestamp): Promise<BillShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markBillPaid(arg0, arg1);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBillPaid(arg0, arg1);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async markInvoicePaid(arg0: bigint, arg1: Timestamp): Promise<InvoiceShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markInvoicePaid(arg0, arg1);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInvoicePaid(arg0, arg1);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBill(arg0: bigint, arg1: CreateBillData): Promise<BillShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(arg0, to_candid_CreateBillData_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(arg0, to_candid_CreateBillData_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: bigint, arg1: CreateCustomerData): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_CreateCustomerData_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_CreateCustomerData_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoice(arg0: bigint, arg1: CreateInvoiceData): Promise<InvoiceShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_CreateInvoiceData_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_CreateInvoiceData_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: bigint, arg1: CreateProductData): Promise<ProductShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplier(arg0: bigint, arg1: CreateSupplierData): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, to_candid_CreateSupplierData_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, to_candid_CreateSupplierData_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadBillAttachment(arg0: bigint, arg1: string): Promise<BillShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBillAttachment(arg0, arg1);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBillAttachment(arg0, arg1);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BillCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillCategory): BillCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_BillShared_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillShared): BillShared {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BillStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillStatus): BillStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerType): CustomerType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_ExtractedBillData_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtractedBillData): ExtractedBillData {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceLineItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceLineItem): InvoiceLineItem {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceShared_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceShared): InvoiceShared {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringFrequency_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringFrequency): RecurringFrequency {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Supplier_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Supplier): Supplier {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_VatRate_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VatRate): VatRate {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecurringFrequency]): RecurringFrequency | null {
    return value.length === 0 ? null : from_candid_RecurringFrequency_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillShared]): BillShared | null {
    return value.length === 0 ? null : from_candid_BillShared_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceShared]): InvoiceShared | null {
    return value.length === 0 ? null : from_candid_InvoiceShared_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductShared]): ProductShared | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Supplier]): Supplier | null {
    return value.length === 0 ? null : from_candid_Supplier_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerType: _CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
}): {
    id: bigint;
    customerType: CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        customerType: from_candid_CustomerType_n23(_uploadFile, _downloadFile, value.customerType),
        name: value.name,
        email: value.email,
        address: value.address,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: _Timestamp;
    customerName: string;
    status: _InvoiceStatus;
    lineItems: Array<_InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: _Timestamp;
    totalVat: number;
    grandTotal: number;
    paidDate: [] | [_Timestamp];
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    recurringFrequency: [] | [_RecurringFrequency];
    subtotal: number;
}): {
    id: bigint;
    issueDate: Timestamp;
    customerName: string;
    status: InvoiceStatus;
    lineItems: Array<InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: Timestamp;
    totalVat: number;
    grandTotal: number;
    paidDate?: Timestamp;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    recurringFrequency?: RecurringFrequency;
    subtotal: number;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        customerName: value.customerName,
        status: from_candid_InvoiceStatus_n34(_uploadFile, _downloadFile, value.status),
        lineItems: from_candid_vec_n36(_uploadFile, _downloadFile, value.lineItems),
        isRecurring: value.isRecurring,
        dueDate: value.dueDate,
        totalVat: value.totalVat,
        grandTotal: value.grandTotal,
        paidDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paidDate)),
        invoiceNumber: value.invoiceNumber,
        notes: value.notes,
        customerId: value.customerId,
        recurringFrequency: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.recurringFrequency)),
        subtotal: value.subtotal
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    unitPrice: number;
    vatAmount: number;
    vatRate: _VatRate;
}): {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    unitPrice: number;
    vatAmount: number;
    vatRate: VatRate;
} {
    return {
        lineTotal: value.lineTotal,
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        vatAmount: value.vatAmount,
        vatRate: from_candid_VatRate_n15(_uploadFile, _downloadFile, value.vatRate)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    address: string;
    notes: string;
    category: _BillCategory;
    phone: string;
}): {
    id: bigint;
    name: string;
    email: string;
    address: string;
    notes: string;
    category: BillCategory;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        address: value.address,
        notes: value.notes,
        category: from_candid_BillCategory_n12(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplierName: [] | [string];
    date: [] | [string];
    invoiceNumber: [] | [string];
    vatAmount: [] | [number];
    confidence: string;
    amount: [] | [number];
}): {
    supplierName?: string;
    date?: string;
    invoiceNumber?: string;
    vatAmount?: number;
    confidence: string;
    amount?: number;
} {
    return {
        supplierName: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.supplierName)),
        date: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.date)),
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.invoiceNumber)),
        vatAmount: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.vatAmount)),
        confidence: value.confidence,
        amount: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invoices: Array<_InvoiceShared>;
    outstandingBalance: number;
}): {
    invoices: Array<InvoiceShared>;
    outstandingBalance: number;
} {
    return {
        invoices: from_candid_vec_n53(_uploadFile, _downloadFile, value.invoices),
        outstandingBalance: value.outstandingBalance
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overdueInvoices: Array<_InvoiceShared>;
    lowStockProducts: Array<_ProductShared>;
    netProfitThisMonth: number;
    billsDueIn14Days: Array<_BillShared>;
    totalCashBalance: number;
    revenueThisMonth: number;
    expensesThisMonth: number;
}): {
    overdueInvoices: Array<InvoiceShared>;
    lowStockProducts: Array<ProductShared>;
    netProfitThisMonth: number;
    billsDueIn14Days: Array<BillShared>;
    totalCashBalance: number;
    revenueThisMonth: number;
    expensesThisMonth: number;
} {
    return {
        overdueInvoices: from_candid_vec_n53(_uploadFile, _downloadFile, value.overdueInvoices),
        lowStockProducts: value.lowStockProducts,
        netProfitThisMonth: value.netProfitThisMonth,
        billsDueIn14Days: from_candid_vec_n50(_uploadFile, _downloadFile, value.billsDueIn14Days),
        totalCashBalance: value.totalCashBalance,
        revenueThisMonth: value.revenueThisMonth,
        expensesThisMonth: value.expensesThisMonth
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bills: Array<_BillShared>;
    outstandingBalance: number;
}): {
    bills: Array<BillShared>;
    outstandingBalance: number;
} {
    return {
        bills: from_candid_vec_n50(_uploadFile, _downloadFile, value.bills),
        outstandingBalance: value.outstandingBalance
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BillStatus;
    supplierName: string;
    date: _Timestamp;
    dueDate: _Timestamp;
    linkedProductIds: Array<bigint>;
    paidDate: [] | [_Timestamp];
    notes: string;
    billNumber: string;
    category: _BillCategory;
    vatAmount: number;
    receiptFileId: [] | [string];
    amount: number;
    supplierId: bigint;
    vatRate: _VatRate;
}): {
    id: bigint;
    status: BillStatus;
    supplierName: string;
    date: Timestamp;
    dueDate: Timestamp;
    linkedProductIds: Array<bigint>;
    paidDate?: Timestamp;
    notes: string;
    billNumber: string;
    category: BillCategory;
    vatAmount: number;
    receiptFileId?: string;
    amount: number;
    supplierId: bigint;
    vatRate: VatRate;
} {
    return {
        id: value.id,
        status: from_candid_BillStatus_n9(_uploadFile, _downloadFile, value.status),
        supplierName: value.supplierName,
        date: value.date,
        dueDate: value.dueDate,
        linkedProductIds: value.linkedProductIds,
        paidDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paidDate)),
        notes: value.notes,
        billNumber: value.billNumber,
        category: from_candid_BillCategory_n12(_uploadFile, _downloadFile, value.category),
        vatAmount: value.vatAmount,
        receiptFileId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.receiptFileId)),
        amount: value.amount,
        supplierId: value.supplierId,
        vatRate: from_candid_VatRate_n15(_uploadFile, _downloadFile, value.vatRate)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Overdue: null;
} | {
    Unpaid: null;
}): BillStatus {
    return "Paid" in value ? BillStatus.Paid : "Overdue" in value ? BillStatus.Overdue : "Unpaid" in value ? BillStatus.Unpaid : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Shipping: null;
} | {
    Rent: null;
} | {
    ProfessionalServices: null;
} | {
    Software: null;
} | {
    Packaging: null;
} | {
    Other: null;
} | {
    Ingredients: null;
} | {
    Marketing: null;
}): BillCategory {
    return "Shipping" in value ? BillCategory.Shipping : "Rent" in value ? BillCategory.Rent : "ProfessionalServices" in value ? BillCategory.ProfessionalServices : "Software" in value ? BillCategory.Software : "Packaging" in value ? BillCategory.Packaging : "Other" in value ? BillCategory.Other : "Ingredients" in value ? BillCategory.Ingredients : "Marketing" in value ? BillCategory.Marketing : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Five: null;
} | {
    Zero: null;
} | {
    Twenty: null;
}): VatRate {
    return "Five" in value ? VatRate.Five : "Zero" in value ? VatRate.Zero : "Twenty" in value ? VatRate.Twenty : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DTC: null;
} | {
    Wholesale: null;
}): CustomerType {
    return "DTC" in value ? CustomerType.DTC : "Wholesale" in value ? CustomerType.Wholesale : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Sent: null;
} | {
    Draft: null;
} | {
    Overdue: null;
}): InvoiceStatus {
    return "Paid" in value ? InvoiceStatus.Paid : "Sent" in value ? InvoiceStatus.Sent : "Draft" in value ? InvoiceStatus.Draft : "Overdue" in value ? InvoiceStatus.Overdue : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Weekly: null;
} | {
    Monthly: null;
}): RecurringFrequency {
    return "Weekly" in value ? RecurringFrequency.Weekly : "Monthly" in value ? RecurringFrequency.Monthly : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceLineItem>): Array<InvoiceLineItem> {
    return value.map((x)=>from_candid_InvoiceLineItem_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillShared>): Array<BillShared> {
    return value.map((x)=>from_candid_BillShared_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceShared>): Array<InvoiceShared> {
    return value.map((x)=>from_candid_InvoiceShared_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Supplier>): Array<Supplier> {
    return value.map((x)=>from_candid_Supplier_n44(_uploadFile, _downloadFile, x));
}
function to_candid_BillCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillCategory): _BillCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBillData_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBillData): _CreateBillData {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCustomerData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCustomerData): _CreateCustomerData {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_CreateInvoiceData_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvoiceData): _CreateInvoiceData {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_CreateSupplierData_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateSupplierData): _CreateSupplierData {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): _CustomerType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceLineItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceLineItem): _InvoiceLineItem {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringFrequency_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringFrequency): _RecurringFrequency {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_VatRate_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VatRate): _VatRate {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerType: CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
}): {
    customerType: _CustomerType;
    name: string;
    email: string;
    address: string;
    notes: string;
    phone: string;
} {
    return {
        customerType: to_candid_CustomerType_n19(_uploadFile, _downloadFile, value.customerType),
        name: value.name,
        email: value.email,
        address: value.address,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplierName: string;
    date: Timestamp;
    dueDate: Timestamp;
    linkedProductIds: Array<bigint>;
    notes: string;
    category: BillCategory;
    vatAmount: number;
    receiptFileId?: string;
    amount: number;
    supplierId: bigint;
    vatRate: VatRate;
}): {
    supplierName: string;
    date: _Timestamp;
    dueDate: _Timestamp;
    linkedProductIds: Array<bigint>;
    notes: string;
    category: _BillCategory;
    vatAmount: number;
    receiptFileId: [] | [string];
    amount: number;
    supplierId: bigint;
    vatRate: _VatRate;
} {
    return {
        supplierName: value.supplierName,
        date: value.date,
        dueDate: value.dueDate,
        linkedProductIds: value.linkedProductIds,
        notes: value.notes,
        category: to_candid_BillCategory_n3(_uploadFile, _downloadFile, value.category),
        vatAmount: value.vatAmount,
        receiptFileId: value.receiptFileId ? candid_some(value.receiptFileId) : candid_none(),
        amount: value.amount,
        supplierId: value.supplierId,
        vatRate: to_candid_VatRate_n5(_uploadFile, _downloadFile, value.vatRate)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: Timestamp;
    customerName: string;
    lineItems: Array<InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: Timestamp;
    totalVat: number;
    grandTotal: number;
    notes: string;
    customerId: bigint;
    recurringFrequency?: RecurringFrequency;
    subtotal: number;
}): {
    issueDate: _Timestamp;
    customerName: string;
    lineItems: Array<_InvoiceLineItem>;
    isRecurring: boolean;
    dueDate: _Timestamp;
    totalVat: number;
    grandTotal: number;
    notes: string;
    customerId: bigint;
    recurringFrequency: [] | [_RecurringFrequency];
    subtotal: number;
} {
    return {
        issueDate: value.issueDate,
        customerName: value.customerName,
        lineItems: to_candid_vec_n27(_uploadFile, _downloadFile, value.lineItems),
        isRecurring: value.isRecurring,
        dueDate: value.dueDate,
        totalVat: value.totalVat,
        grandTotal: value.grandTotal,
        notes: value.notes,
        customerId: value.customerId,
        recurringFrequency: value.recurringFrequency ? candid_some(to_candid_RecurringFrequency_n30(_uploadFile, _downloadFile, value.recurringFrequency)) : candid_none(),
        subtotal: value.subtotal
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    unitPrice: number;
    vatAmount: number;
    vatRate: VatRate;
}): {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: bigint;
    unitPrice: number;
    vatAmount: number;
    vatRate: _VatRate;
} {
    return {
        lineTotal: value.lineTotal,
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        vatAmount: value.vatAmount,
        vatRate: to_candid_VatRate_n5(_uploadFile, _downloadFile, value.vatRate)
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    address: string;
    notes: string;
    category: BillCategory;
    phone: string;
}): {
    name: string;
    email: string;
    address: string;
    notes: string;
    category: _BillCategory;
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        address: value.address,
        notes: value.notes,
        category: to_candid_BillCategory_n3(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): {
    DTC: null;
} | {
    Wholesale: null;
} {
    return value == CustomerType.DTC ? {
        DTC: null
    } : value == CustomerType.Wholesale ? {
        Wholesale: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringFrequency): {
    Weekly: null;
} | {
    Monthly: null;
} {
    return value == RecurringFrequency.Weekly ? {
        Weekly: null
    } : value == RecurringFrequency.Monthly ? {
        Monthly: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillCategory): {
    Shipping: null;
} | {
    Rent: null;
} | {
    ProfessionalServices: null;
} | {
    Software: null;
} | {
    Packaging: null;
} | {
    Other: null;
} | {
    Ingredients: null;
} | {
    Marketing: null;
} {
    return value == BillCategory.Shipping ? {
        Shipping: null
    } : value == BillCategory.Rent ? {
        Rent: null
    } : value == BillCategory.ProfessionalServices ? {
        ProfessionalServices: null
    } : value == BillCategory.Software ? {
        Software: null
    } : value == BillCategory.Packaging ? {
        Packaging: null
    } : value == BillCategory.Other ? {
        Other: null
    } : value == BillCategory.Ingredients ? {
        Ingredients: null
    } : value == BillCategory.Marketing ? {
        Marketing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VatRate): {
    Five: null;
} | {
    Zero: null;
} | {
    Twenty: null;
} {
    return value == VatRate.Five ? {
        Five: null
    } : value == VatRate.Zero ? {
        Zero: null
    } : value == VatRate.Twenty ? {
        Twenty: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvoiceLineItem>): Array<_InvoiceLineItem> {
    return value.map((x)=>to_candid_InvoiceLineItem_n28(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
